// <auto-generated />
using System;
using W2K.Config.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace W2K.Config.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20250617054234_Config_Initial")]
    partial class Config_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dfi")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("W2K.Config.Entities.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(4);

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Configs", "dfi");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_Configs", "dfi");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Config.Entities.OfficeConfigField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(6);

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnOrder(8);

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit")
                        .HasColumnOrder(13);

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit")
                        .HasColumnOrder(12);

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(10);

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(5);

                    b.Property<string>("OfficeType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("RegexValidator")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(11);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.HasKey("Id");

                    b.ToTable("OfficeConfigFields", "dfi");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_OfficeConfigFields", "dfi");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Config.Entities.OfficeConfigFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<int>("FieldId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<int>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("FieldId", "OfficeId")
                        .IsUnique()
                        .HasDatabaseName("IX_OfficeConfigFieldValues_FieldId_OfficeId");

                    b.ToTable("OfficeConfigFieldValues", "dfi");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_OfficeConfigFieldValues", "dfi");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Config.Entities.OfficeConfigField", b =>
                {
                    b.OwnsMany("W2K.Config.Entities.FieldValue", "FieldValues", b1 =>
                        {
                            b1.Property<int>("OfficeConfigFieldId")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<short>("DisplayOrder")
                                .HasColumnType("smallint");

                            b1.Property<string>("Text")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OfficeConfigFieldId", "__synthesizedOrdinal");

                            b1.ToTable("OfficeConfigFields", "dfi");

                            b1.ToJson("FieldValues");

                            b1.WithOwner()
                                .HasForeignKey("OfficeConfigFieldId");
                        });

                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("W2K.Config.Entities.OfficeConfigFieldValue", b =>
                {
                    b.HasOne("W2K.Config.Entities.OfficeConfigField", "Field")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("W2K.Config.Entities.OfficeConfigField", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
