// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W2K.Files.Persistence.Context;

#nullable disable

namespace W2K.Files.Migrations
{
    [DbContext(typeof(FilesDbContext))]
    partial class FilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("files")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("W2K.Files.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(3)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential\",\"InformationType\":\"Networking\",\"Rank\":\"HIGH\"}");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.HasKey("Id");

                    b.ToTable("Files", "files");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_Files", "files");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Files.Entities.File", b =>
                {
                    b.OwnsMany("W2K.Common.ValueObjects.Tag", "Tags", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnOrder(1);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("FileId")
                                .HasColumnType("int")
                                .HasColumnOrder(2);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(3);

                            b1.Property<DateTime>("PeriodEnd")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTime>("PeriodStart")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodStart");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("FileId", "Name")
                                .IsUnique()
                                .HasDatabaseName("IX_FileTags_FileId_Name");

                            b1.ToTable("FileTags", "files");

                            b1
                                .ToTable(tb => tb.IsTemporal(ttb =>
                                    {
                                        ttb.UseHistoryTable("History_FileTags");
                                        ttb
                                            .HasPeriodStart("PeriodStart")
                                            .HasColumnName("PeriodStart");
                                        ttb
                                            .HasPeriodEnd("PeriodEnd")
                                            .HasColumnName("PeriodEnd");
                                    }))
                                .HasAnnotation("HistoryRetention", 90);

                            b1.WithOwner()
                                .HasForeignKey("FileId");
                        });

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
