// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W2K.Common.Persistence.Encryption;
using W2K.Identity.Persistence.Context;

#nullable disable

namespace W2K.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("id")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolesPermissions", "id");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_RolesPermissions", "id");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Identity.Entities.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnnualRevenue")
                        .HasColumnType("int")
                        .HasColumnOrder(17);

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(16);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("Code")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<string>("Fax")
                        .HasMaxLength(108)
                        .HasColumnType("nvarchar(108)")
                        .HasColumnOrder(9)
                        .HasAnnotation("Encryption", EncryptionAlgorithm.AES256)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                    b.Property<string>("HowHeard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(19);

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnOrder(22);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<bool>("IsEnrollmentCompleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(20);

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit")
                        .HasColumnOrder(21);

                    b.Property<DateTime?>("LastLoginDateTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(26);

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(7);

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(11)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Other\",\"Rank\":\"NONE\"}");

                    b.Property<string>("LicenseState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<DateOnly?>("OriginalLicenseDate")
                        .HasColumnType("date")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(108)
                        .HasColumnType("nvarchar(108)")
                        .HasColumnOrder(8)
                        .HasAnnotation("Encryption", EncryptionAlgorithm.AES256)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(18);

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(108)
                        .HasColumnType("nvarchar(108)")
                        .HasColumnOrder(15)
                        .HasAnnotation("Encryption", EncryptionAlgorithm.AES256)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential\",\"InformationType\":\"National ID\",\"Rank\":\"CRITICAL\"}");

                    b.Property<string>("Tenant")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(3);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(2);

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(25);

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(24);

                    b.Property<string>("UtmSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(23);

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(10);

                    b.Property<short?>("YearsCurrentOwnership")
                        .HasColumnType("smallint")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.ToTable("Offices", "id");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_Offices", "id");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Identity.Entities.OfficeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("InviteAcceptedDateTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<bool>("IsInviteProcessed")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsInvited")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<int>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("OfficeUsers", "id");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_OfficeUsers", "id");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Identity.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", "id");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_Permissions", "id");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Identity.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(5);

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("OfficeType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Roles", "id");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_Roles", "id");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("W2K.Identity.Entities.SessionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(5376)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4)
                        .HasAnnotation("Encryption", EncryptionAlgorithm.AES256);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<string>("OldSessionId")
                        .HasMaxLength(364)
                        .HasColumnType("nvarchar(364)")
                        .HasColumnOrder(6)
                        .HasAnnotation("Encryption", EncryptionAlgorithm.AES256);

                    b.Property<string>("SessionId")
                        .HasMaxLength(364)
                        .HasColumnType("nvarchar(364)")
                        .HasColumnOrder(3)
                        .HasAnnotation("Encryption", EncryptionAlgorithm.AES256);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("SessionLogs", "id");
                });

            modelBuilder.Entity("W2K.Identity.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(91)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(94)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(92);

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(93);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(5)
                        .HasAnnotation("DynamicDataMask", "default()")
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential\",\"InformationType\":\"Contact Info\",\"Rank\":\"MEDIUM\"}");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential\",\"InformationType\":\"Name\",\"Rank\":\"MEDIUM\"}");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(81);

                    b.Property<DateTime?>("LastLoginDateTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("LastLogoutDateTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential\",\"InformationType\":\"Name\",\"Rank\":\"MEDIUM\"}");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(6)
                        .HasAnnotation("DynamicDataMask", "default()")
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential\",\"InformationType\":\"Contact Info\",\"Rank\":\"MEDIUM\"}");

                    b.Property<DateTime?>("ModifyDateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(95)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(98)
                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(96);

                    b.Property<string>("ModifyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(97);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(99);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasFilter("[ProviderId] IS NOT NULL");

                    b.ToTable("Users", "id");

                    b
                        .ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("History_Users", "id");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }))
                        .HasAnnotation("HistoryRetention", 90);
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("W2K.Identity.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("W2K.Identity.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("W2K.Identity.Entities.Office", b =>
                {
                    b.OwnsMany("W2K.Common.ValueObjects.Address", "Addresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnOrder(1);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(4)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                            b1.Property<string>("Address2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(5)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(6)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(10)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                            b1.Property<string>("County")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(7)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                            b1.Property<string>("GooglePlaceId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(12);

                            b1.Property<int>("OfficeId")
                                .HasColumnType("int")
                                .HasColumnOrder(2);

                            b1.Property<DateTime>("PeriodEnd")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTime>("PeriodStart")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodStart");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(8)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                            b1.Property<string>("TimeZone")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(11);

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnOrder(3);

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnOrder(9)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Public\",\"InformationType\":\"Contact Info\",\"Rank\":\"NONE\"}");

                            b1.HasKey("Id");

                            b1.HasIndex("OfficeId");

                            b1.ToTable("OfficeAddresses", "id");

                            b1
                                .ToTable(tb => tb.IsTemporal(ttb =>
                                    {
                                        ttb.UseHistoryTable("History_OfficeAddresses");
                                        ttb
                                            .HasPeriodStart("PeriodStart")
                                            .HasColumnName("PeriodStart");
                                        ttb
                                            .HasPeriodEnd("PeriodEnd")
                                            .HasColumnName("PeriodEnd");
                                    }))
                                .HasAnnotation("HistoryRetention", 90);

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.OwnsMany("W2K.Identity.Entities.OfficeBankAccount", "BankAccounts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnOrder(1);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(6)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Banking\",\"Rank\":\"HIGH\"}");

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(7)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Banking\",\"Rank\":\"CRITICAL\"}");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(4)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Banking\",\"Rank\":\"HIGH\"}");

                            b1.Property<DateTime?>("CreateDateTimeUtc")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasColumnOrder(91)
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<string>("CreateSource")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(94)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                            b1.Property<int?>("CreateUserId")
                                .HasColumnType("int")
                                .HasColumnOrder(92);

                            b1.Property<string>("CreateUserName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(93);

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("bit")
                                .HasColumnOrder(8);

                            b1.Property<DateTime?>("ModifyDateTimeUtc")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasColumnOrder(95)
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<string>("ModifySource")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(98)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                            b1.Property<int?>("ModifyUserId")
                                .HasColumnType("int")
                                .HasColumnOrder(96);

                            b1.Property<string>("ModifyUserName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(97);

                            b1.Property<int>("OfficeId")
                                .HasColumnType("int")
                                .HasColumnOrder(2);

                            b1.Property<DateTime>("PeriodEnd")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTime>("PeriodStart")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodStart");

                            b1.Property<string>("RoutingNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(5)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Banking\",\"Rank\":\"CRITICAL\"}");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnOrder(3);

                            b1.HasKey("Id");

                            b1.HasIndex("OfficeId");

                            b1.ToTable("OfficeBankAccounts", "id");

                            b1
                                .ToTable(tb => tb.IsTemporal(ttb =>
                                    {
                                        ttb.UseHistoryTable("History_OfficeBankAccounts");
                                        ttb
                                            .HasPeriodStart("PeriodStart")
                                            .HasColumnName("PeriodStart");
                                        ttb
                                            .HasPeriodEnd("PeriodEnd")
                                            .HasColumnName("PeriodEnd");
                                    }))
                                .HasAnnotation("HistoryRetention", 90);

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.OwnsMany("W2K.Identity.Entities.OfficeGroup", "Groups", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnOrder(1);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("OfficeId")
                                .HasColumnType("int")
                                .HasColumnOrder(2);

                            b1.Property<int>("ParentOfficeId")
                                .HasColumnType("int")
                                .HasColumnOrder(3);

                            b1.HasKey("Id");

                            b1.HasIndex("OfficeId");

                            b1.ToTable("OfficeGroups", "id");

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.OwnsMany("W2K.Identity.Entities.OfficeOwner", "Owners", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnOrder(1);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("AnnualIncome")
                                .HasColumnType("int")
                                .HasColumnOrder(11);

                            b1.Property<DateTime?>("CreateDateTimeUtc")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasColumnOrder(91)
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<string>("CreateSource")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(94)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                            b1.Property<int?>("CreateUserId")
                                .HasColumnType("int")
                                .HasColumnOrder(92);

                            b1.Property<string>("CreateUserName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(93);

                            b1.Property<string>("DOB")
                                .HasMaxLength(108)
                                .HasColumnType("nvarchar(108)")
                                .HasColumnOrder(8)
                                .HasAnnotation("Encryption", EncryptionAlgorithm.AES256)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Date of Birth\",\"Rank\":\"CRITICAL\"}");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(6)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnOrder(3)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Name\",\"Rank\":\"MEDIUM\"}");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnOrder(5)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Name\",\"Rank\":\"MEDIUM\"}");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnOrder(4)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Name\",\"Rank\":\"MEDIUM\"}");

                            b1.Property<string>("MobilePhone")
                                .HasMaxLength(108)
                                .HasColumnType("nvarchar(108)")
                                .HasColumnOrder(7)
                                .HasAnnotation("Encryption", EncryptionAlgorithm.AES256)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                            b1.Property<DateTime?>("ModifyDateTimeUtc")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasColumnOrder(95)
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<string>("ModifySource")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnOrder(98)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Confidential - GDPR\",\"InformationType\":\"Networking\",\"Rank\":\"MEDIUM\"}");

                            b1.Property<int?>("ModifyUserId")
                                .HasColumnType("int")
                                .HasColumnOrder(96);

                            b1.Property<string>("ModifyUserName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(97);

                            b1.Property<int?>("NetWorth")
                                .HasColumnType("int")
                                .HasColumnOrder(12);

                            b1.Property<int>("OfficeId")
                                .HasColumnType("int")
                                .HasColumnOrder(2);

                            b1.Property<short>("Ownership")
                                .HasColumnType("smallint")
                                .HasColumnOrder(10);

                            b1.Property<DateTime>("PeriodEnd")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTime>("PeriodStart")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodStart");

                            b1.Property<string>("SSN")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnOrder(9)
                                .HasAnnotation("Encryption", EncryptionAlgorithm.AES256)
                                .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"National ID\",\"Rank\":\"CRITICAL\"}");

                            b1.HasKey("Id");

                            b1.HasIndex("OfficeId");

                            b1.ToTable("OfficeOwners", "id");

                            b1
                                .ToTable(tb => tb.IsTemporal(ttb =>
                                    {
                                        ttb.UseHistoryTable("History_OfficeOwners");
                                        ttb
                                            .HasPeriodStart("PeriodStart")
                                            .HasColumnName("PeriodStart");
                                        ttb
                                            .HasPeriodEnd("PeriodEnd")
                                            .HasColumnName("PeriodEnd");
                                    }))
                                .HasAnnotation("HistoryRetention", 90);

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");

                            b1.OwnsOne("W2K.Common.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnOrder(1);

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Address1")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnOrder(22)
                                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                                    b2.Property<string>("Address2")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnOrder(23)
                                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnOrder(24)
                                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnOrder(28)
                                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                                    b2.Property<string>("County")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnOrder(25)
                                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                                    b2.Property<string>("GooglePlaceId")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnOrder(30);

                                    b2.Property<int>("OfficeOwnerId")
                                        .HasColumnType("int")
                                        .HasColumnOrder(2);

                                    b2.Property<DateTime>("PeriodEnd")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("datetime2")
                                        .HasColumnName("PeriodEnd");

                                    b2.Property<DateTime>("PeriodStart")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("datetime2")
                                        .HasColumnName("PeriodStart");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnOrder(26)
                                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                                    b2.Property<string>("TimeZone")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnOrder(29);

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(25)
                                        .HasColumnType("nvarchar(25)")
                                        .HasColumnOrder(21);

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnOrder(27)
                                        .HasAnnotation("SensitivityClassification", "{\"Label\":\"Highly Confidential - GDPR\",\"InformationType\":\"Contact Info\",\"Rank\":\"HIGH\"}");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OfficeOwnerId")
                                        .IsUnique();

                                    b2.ToTable("OfficeOwnerAddress", "id");

                                    b2
                                        .ToTable(tb => tb.IsTemporal(ttb =>
                                            {
                                                ttb.UseHistoryTable("History_OfficeOwnerAddress");
                                                ttb
                                                    .HasPeriodStart("PeriodStart")
                                                    .HasColumnName("PeriodStart");
                                                ttb
                                                    .HasPeriodEnd("PeriodEnd")
                                                    .HasColumnName("PeriodEnd");
                                            }))
                                        .HasAnnotation("HistoryRetention", 90);

                                    b2.WithOwner()
                                        .HasForeignKey("OfficeOwnerId");
                                });

                            b1.Navigation("Address");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("Groups");

                    b.Navigation("Owners");
                });

            modelBuilder.Entity("W2K.Identity.Entities.OfficeUser", b =>
                {
                    b.HasOne("W2K.Identity.Entities.Office", "Office")
                        .WithMany("Users")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("W2K.Identity.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("W2K.Identity.Entities.User", "User")
                        .WithMany("Offices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("W2K.Identity.Entities.Office", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("W2K.Identity.Entities.User", b =>
                {
                    b.Navigation("Offices");
                });
#pragma warning restore 612, 618
        }
    }
}
